services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MODE=api
    depends_on:
      - nats

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODE=worker
    depends_on:
      - nats

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "-js -m 8222"